export const GLASS_CATEGORIES = [
  'Incolor',
  'Colorido',
  'Extra Claro',
  'Impresso',
  'Fosco',
  'Laminado Incolor',
  'Laminado Acustico',
  'Laminado Colorido',
  'Laminado Opalino',
  'Laminado Baixo Emissivo',
  'Espelhado',
  'Baixo Emissivo',
  'Controlo Solar',
  'Cool Lite',
  'Sunguard',
];
