export const GLASS_TYPES = [
  {
    typeId: 'VFC',
    label: 'VFClaro',
    category: 'incolor',
    thickness: ['4', '5', '6', '8', '10'],
    temper: 'optional',
  },

  {
    typeId: 'VFB',
    label: 'VFBronze',
    category: 'colorido',
    thickness: ['4', '5', '6', '8', '10'],
    temper: 'optional',
  },
  {
    typeId: 'VFG',
    label: 'VFGris',
    category: 'colorido',
    thickness: ['4', '5', '6', '8', '10'],
    temper: 'optional',
  },
  {
    typeId: 'VFV',
    label: 'VFVerde',
    category: 'colorido',
    thickness: ['4', '5', '6', '8', '10'],
    temper: 'optional',
  },

  {
    typeId: 'diamant',
    label: 'V. Diamant',
    category: 'extraClaro',
    thickness: ['4', '5', '6', '8', '10'],
    temper: 'optional',
  },

  {
    typeId: 'crepe',
    label: 'V. Crepe',
    category: 'impresso',
    thickness: ['4', '6'],
    temper: 'optional',
  },
  {
    typeId: 'aramado',
    label: 'V. Aramado',
    category: 'impresso',
    thickness: ['6'],
    temper: 'forbidden',
  },

  {
    typeId: 'fosco',
    label: 'V. Fosco',
    category: 'fosco',
    thickness: ['4', '5', '6', '8'],
    temper: 'optional',
  },

  {
    typeId: 'lamInc',
    label: 'V. Lam. Inc.',
    category: 'laminadoIncolor',
    thickness: ['3+3', '4+4', '5+5', '6+6'],
    temper: 'forbidden',
  },

  {
    typeId: 'lamS',
    label: 'V. Lam. Sil.',
    category: 'laminadoAcustico',
    thickness: ['3+3', '4+4', '5+5', '6+6'],
    temper: 'forbidden',
  },

  {
    typeId: 'lamO',
    label: 'V. Lam. Opalino',
    category: 'laminadoOpalino',
    thickness: ['3+3', '4+4', '5+5', '6+6'],
    temper: 'forbidden',
  },

  {
    typeId: 'lamB',
    label: 'V. Lam. Bronze',
    category: 'laminadoColorido',
    thickness: ['3+3', '4+4', '5+5', '6+6'],
    temper: 'forbidden',
  },
  {
    typeId: 'lamG',
    label: 'V. Lam. Gris',
    category: 'laminadoColorido',
    thickness: ['3+3', '4+4', '5+5', '6+6'],
    temper: 'forbidden',
  },
  {
    typeId: 'lamV',
    label: 'V. Lam. Verde',
    category: 'laminadoColorido',
    thickness: ['3+3', '4+4', '5+5', '6+6'],
    temper: 'forbidden',
  },

  {
    typeId: 'lamXN',
    label: 'V. Lam. Pl. XN',
    category: 'laminadoBaixoEmissivo',
    thickness: ['4+4', '6+6'],
    temper: 'forbidden',
  },
  {
    typeId: 'lamCG',
    label: 'V. Lam. Climaguard Premium',
    category: 'laminadoBaixoEmissivo',
    thickness: ['4+4'],
    temper: 'forbidden',
  },
  {
    typeId: 'lam4S',
    label: 'V. Lam. Planitherm 4s',
    category: 'laminadoBaixoEmissivo',
    thickness: ['4+4'],
    temper: 'forbidden',
  },
  {
    typeId: 'lamGS',
    label: 'V. Lam. Guardian Sun',
    category: 'laminadoBaixoEmissivo',
    thickness: ['4+4'],
    temper: 'forbidden',
  },

  {
    typeId: 'stopSol',
    label: 'V. Stop Sol Claro',
    category: 'espelhado',
    thickness: ['5', '6'],
    temper: 'optional',
  },
  {
    typeId: 'mirastar',
    label: 'V. Mirastar',
    category: 'espelhado',
    thickness: ['6', '8'],
    temper: 'optional',
  },

  {
    typeId: 'plXN',
    label: 'V. Planitherm XN',
    category: 'baixoEmissivo',
    thickness: ['4', '6', '8'],
    temper: 'optional',
  },
  {
    typeId: 'plU',
    label: 'V. Planitherm Ultra N',
    category: 'baixoEmissivo',
    thickness: ['4', '6', '8'],
    temper: 'optional',
  },
  {
    typeId: 'climaguard',
    label: 'V. Climaguard Premium',
    category: 'baixoEmissivo',
    thickness: ['4', '6'],
    temper: 'optional',
  },

  {
    typeId: 'pl4s',
    label: 'V. Planitherm 4s',
    category: 'controloSolar',
    thickness: ['4', '6', '8'],
    temper: 'optional',
  },

  {
    typeId: 'plOne',
    label: 'V. Planitherm One',
    category: 'controloSolar',
    thickness: ['6', '8'],
    temper: 'optional',
  },

  {
    typeId: 'planistar',
    label: 'V. Planistar',
    category: 'controloSolar',
    thickness: ['6', '8'],
    temper: 'optional',
  },

  {
    typeId: 'GS',
    label: 'V. Guardian Sun',
    category: 'controloSolar',
    thickness: ['4', '6', '8'],
    temper: 'optional',
  },

  {
    typeId: 'ST120',
    label: 'V. ST120',
    category: 'coolLite',
    thickness: ['6', '8'],
    temper: 'required',
  },
  {
    typeId: 'ST136',
    label: 'V. ST136',
    category: 'coolLite',
    thickness: ['6', '8'],
    temper: 'required',
  },
  {
    typeId: 'ST150',
    label: 'V. ST150',
    category: 'coolLite',
    thickness: ['6', '8'],
    temper: 'required',
  },
  {
    typeId: 'SKN144',
    label: 'V. SKN144',
    category: 'coolLite',
    thickness: ['6', '8'],
    temper: 'required',
  },
  {
    typeId: 'SKN154',
    label: 'V. SKN154',
    category: 'coolLite',
    thickness: ['6', '8'],
    temper: 'required',
  },
  {
    typeId: 'SKN165',
    label: 'V. SKN165',
    category: 'coolLite',
    thickness: ['6', '8'],
    temper: 'required',
  },
  {
    typeId: 'SKN176',
    label: 'V. SKN176',
    category: 'coolLite',
    thickness: ['6', '8'],
    temper: 'required',
  },
  {
    typeId: 'SKN183',
    label: 'V. SKN183',
    category: 'coolLite',
    thickness: ['6', '8'],
    temper: 'required',
  },
  {
    typeId: 'xtreme5022',
    label: 'V. Xtreme 50/22',
    category: 'coolLite',
    thickness: ['6', '8'],
    temper: 'required',
  },
  {
    typeId: 'xtreme6028',
    label: 'V. Xtreme 60/28',
    category: 'coolLite',
    thickness: ['6', '8'],
    temper: 'required',
  },
  {
    typeId: 'xtreme6129',
    label: 'V. Xtreme 61/29',
    category: 'coolLite',
    thickness: ['6', '8'],
    temper: 'required',
  },
  {
    typeId: 'xtreme7033',
    label: 'V. Xtreme 70/33',
    category: 'coolLite',
    thickness: ['6', '8'],
    temper: 'required',
  },

  {
    typeId: 'sn2918',
    label: 'V. SN 29/18 HT',
    category: 'sunguard',
    thickness: ['6', '8'],
    temper: 'required',
  },
  {
    typeId: 'sn4023',
    label: 'V. SN 40/23 HT',
    category: 'sunguard',
    thickness: ['6', '8'],
    temper: 'required',
  },
  {
    typeId: 'sn51',
    label: 'V. SN 51 HT',
    category: 'sunguard',
    thickness: ['6', '8'],
    temper: 'required',
  },
  {
    typeId: 'sn7035',
    label: 'V. SN 70/35 HT',
    category: 'sunguard',
    thickness: ['6', '8'],
    temper: 'required',
  },
  {
    typeId: 'sn7037',
    label: 'V. SN 70/37 HT',
    category: 'sunguard',
    thickness: ['6', '8'],
    temper: 'required',
  },
  {
    typeId: 'sn70s',
    label: 'V. SN 70S HT',
    category: 'sunguard',
    thickness: ['6', '8'],
    temper: 'required',
  },
  {
    typeId: 'snx50',
    label: 'V. SNX 50 HT',
    category: 'sunguard',
    thickness: ['6', '8'],
    temper: 'required',
  },
  {
    typeId: 'snx60',
    label: 'V. SNX 60 HT',
    category: 'sunguard',
    thickness: ['6', '8'],
    temper: 'required',
  },
  {
    typeId: 'snx70',
    label: 'V. SNX 70 HT',
    category: 'sunguard',
    thickness: ['6', '8'],
    temper: 'required',
  },
  {
    typeId: 'hp5032',
    label: 'V. HP 50/32',
    category: 'sunguard',
    thickness: ['6', '8'],
    temper: 'required',
  },
];
