export const GLASS_CATEGORIES = [
  { label: 'Incolor', isLaminated: false },
  { label: 'Colorido', isLaminated: false },
  { label: 'Extra Claro', isLaminated: false },
  { label: 'Impresso', isLaminated: false },
  { label: 'Fosco', isLaminated: false },
  { label: 'Laminado Incolor', isLaminated: true },
  { label: 'Laminado Acustico', isLaminated: true },
  { label: 'Laminado Colorido', isLaminated: true },
  { label: 'Laminado Opalino', isLaminated: true },
  { label: 'Laminado Baixo Emissivo', isLaminated: true },
  { label: 'Espelhado', isLaminated: false },
  { label: 'Baixo Emissivo', isLaminated: false },
  { label: 'Controlo Solar', isLaminated: false },
  { label: 'Cool Lite', isLaminated: false },
  { label: 'Sunguard', isLaminated: false },
];
